version: '3'
services:
  backend:
    env_file:
      - .env
    build: .
    ports:
      - 5555:5555
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  postgres:
  redis:
